ip_addr: {{.IP}}
remote_host: {{.Host}}
user_agent: {{.UserAgent}}
port: {{.Port}}
lang: {{.Lang}}
connection: {{.Connection}}
keep_alive: {{.Keepalive}}
encoding: {{.Encoding}}
mime: {{.Mime}}
charset: {{.Charset}}
via: {{.Via}}
forwarded: {{.Forwarded}}
