name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        env GOOS=linux GOARCH=amd64 go build -o linux-amd64/ifconfig -ldflags="-s" .
        env GOOS=linux GOARCH=arm GOARM=5 go build -o linux-arm-5/ifconfig -ldflags="-s" .
        env GOOS=linux GOARCH=arm GOARM=6 go build -o linux-arm-6/ifconfig -ldflags="-s" .
        env GOOS=linux GOARCH=arm GOARM=7 go build -o linux-arm-7/ifconfig -ldflags="-s" .
        env GOOS=linux GOARCH=arm64 go build -o linux-arm64/ifconfig -ldflags="-s" .
        env GOOS=darwin GOARCH=amd64 go build -o darwin-amd64/ifconfig -ldflags="-s" .
        env GOOS=darwin GOARCH=arm64 go build -o darwin-arm64/ifconfig -ldflags="-s" .
        env GOOS=windows GOARCH=amd64 go build -o windows-amd64/ifconfig.exe -ldflags="-s" .
        env GOOS=freebsd GOARCH=amd64 go build -o freebsd-amd64/ifconfig -ldflags="-s" .
        env GOOS=openbsd GOARCH=amd64 go build -o openbsd-amd64/ifconfig -ldflags="-s" .
        env GOOS=netbsd GOARCH=amd64 go build -o netbsd-amd64/ifconfig -ldflags="-s" .
        env GOOS=dragonfly GOARCH=amd64 go build -o dragonfly-amd64/ifconfig -ldflags="-s" .
      
    - name: Upload artifact ifconfig-linux-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ifconfig-linux-amd64
        # Directory containing files to upload
        path: linux-amd64

    - name: Upload artifact ifconfig-linux-arm-5
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ifconfig-linux-arm-5
        # Directory containing files to upload
        path: linux-arm-5

    - name: Upload artifact ifconfig-linux-arm-6
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ifconfig-linux-arm-6
        # Directory containing files to upload
        path: linux-arm-6

    - name: Upload artifact ifconfig-linux-arm-7
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ifconfig-linux-arm-7
        # Directory containing files to upload
        path: linux-arm-7

    - name: Upload artifact ifconfig-linux-arm64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ifconfig-linux-arm64
        # Directory containing files to upload
        path: linux-arm64

    - name: Upload artifact ifconfig-darwin-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ifconfig-darwin-amd64
        # Directory containing files to upload
        path: darwin-amd64

    - name: Upload artifact ifconfig-darwin-arm64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ifconfig-darwin-arm64
        # Directory containing files to upload
        path: darwin-arm64

    - name: Upload artifact ifconfig-dragonfly-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ifconfig-dragonfly-amd64
        # Directory containing files to upload
        path: dragonfly-amd64

    - name: Upload artifact ifconfig-openbsd-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ifconfig-openbsd-amd64
        # Directory containing files to upload
        path: openbsd-amd64

    - name: Upload artifact ifconfig-netbsd-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ifconfig-netbsd-amd64
        # Directory containing files to upload
        path: netbsd-amd64

    - name: Upload artifact ifconfig-freebsd-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ifconfig-freebsd-amd64
        # Directory containing files to upload
        path: freebsd-amd64

    - name: Upload artifact ifconfig-windows-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ifconfig-windows-amd64
        # Directory containing files to upload
        path: windows-amd64
